### ISSUE TITLE
Field Filters not working for text strings

### ISSUE THREAD

**Issue by jaronheard** [kiniadit/passenger_census_api#1]
Examples:
http://0.0.0.0:8000/api/passenger-census/?public_location_description=SW
http://0.0.0.0:8000/api/passenger-census/?service_key=S

Seems to work for search, just not for field filters

**Comment by kiniadit** [comment]
field filters are exact matches and will only match the full string value. 

also the reason http://localhost:8000/api/passenger-census/?summary_begin_date=%22SW%206th%20&%20Salmon%22 doesn't work is because the browser encodes spaces automatically but doesn't do so with ampersands. the fix for this is to use encoding for [reserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) when building the query parameters.

**Comment by kiniadit** [comment]
issue fixed in https://github.com/kiniadit/passenger_census_api/blob/master/README.md
